    <div>
      <a href="http://avsbq.org">HOME</a> |
      <a href="http://archive.avsbq.org">ARCHIVE</a> |
      <a href="http://icons.avsbq.org">ICONs</a> |
      <a href="http://mal.avsbq.org">MAL !<a> |
      <a href="http://language.avsbq.org">LANG.</a> |
      <a href="http://links.avsbq.org">LINKs</a> |
      <a href="http://to-do.avsbq.org">TO-DO</a> |
      <a href="http://handbook.avsbq.org"><span style="color: red;"><b>HANDBOOK</b></span></a> 
    </div>

<div><a href="http://avsbq.org/.reach">REACH</a> - <a href="http://avsbq.org/.give">GIVE</a> - <a href="/sitemap">SITEMAP</a>
<br>
<input type="text" id="searchBar" placeholder="Search...">
<div id="searchResults"></div>
<script src="http://handbook.avsbq.org/s.js"></script>
</div>
