    <div>
      <a href="http://avsbq.org">HOME</a> |
      <a href="http://archive.avsbq.org">ARCHIVE</a> |
      <a href="http://icons.avsbq.org">ICONs</a> |
      <a href="http://mal.avsbq.org"><span style="color: red;"><b>MAL !</b></span></a> |
      <a href="http://language.avsbq.org">LANG.</a> |
      <a href="http://links.avsbq.org">LINKs</a> |
      <a href="http://to-do.avsbq.org">TO-DO</a> |
      <a href="http://handbook.avsbq.org">HANDBOOK</a> 
    </div>

<div><a href="http://avsbq.org/.reach">REACH</a> - <a href="http://avsbq.org/.give">GIVE</a> - <a href="/sitemap">SITEMAP</a></div>
